from setuptools import setup, find_packages

setup(
    name="synthetic-opinion-lab",
    version="0.1.0",
    author="Synthetic Opinion Lab",
    description="A framework for generating synthetic public opinion survey data",
    long_description=open("README.md").read() if os.path.exists("README.md") else "",
    long_description_content_type="text/markdown",
    packages=find_packages(),
    python_requires=">=3.8",
    install_requires=[
        "pandas>=2.0.0",
        "numpy>=1.24.0",
        "scipy>=1.10.0",
        "pyreadstat>=1.2.0",
        "pyarrow>=12.0.0",
        "scikit-learn>=1.3.0",
        "matplotlib>=3.7.0",
        "seaborn>=0.12.0",
        "plotly>=5.15.0",
        "requests>=2.31.0",
        "httpx>=0.24.0",
        "pydantic>=2.0.0",
        "PyYAML>=6.0.1",
        "tqdm>=4.65.0",
        "jinja2>=3.1.0",
    ],
    extras_require={
        "dev": ["pytest", "black", "flake8", "mypy"],
    },
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
)